Allow more schema attributes to be updated
replikativ/datahike pull request #352
Opened 2021-06-30 13:20 UTC by MrEbbinghaus

This MR allows the update of any non-`db` namespaced attribute key

- [x] any non-`db` namespaced attribute key
- [x] The `:db/doc` key
- [ ] The `:db/cardinality`key
- [ ] The `:db/noHistory` key

Closes https://github.com/replikativ/datahike/issues/345

2021-06-30 13:23 UTC, MrEbbinghaus commented
@kordano I don't think there is anything preventing `:db/cardinality` or `:db/noHistory` from being updated, at least as far as I would assume with my sparse knowledge of the Datahike implementation. What do you think?

2021-06-30 13:41 UTC, kordano commented
Both changes are fine. There might be some old history data when you set `:db/noHistory` but this should be transparent the database engineer when looking at the schema changes.

2021-06-30 13:42 UTC, kordano commented
And thanks for the PR, happy to review as soon as you like. :)

2021-06-30 13:47 UTC, MrEbbinghaus commented
@kordano Added the two attributes as well. Feel free to review.

2021-07-01 12:47 UTC, kordano requested changes
Looks good @MrEbbinghaus. Could you add a small test that asserts changing `:db/doc`, `:db/noHistory`, and `:db/isComponent` to the `datahike.test.schema` test namespace?

2021-07-02 10:33 UTC, MrEbbinghaus commented
Ok, will do it on the weekend

2021-07-03 12:08 UTC, MrEbbinghaus commented
@kordano I removed the check to allow non `db` namespaced attributes, as that would involve other parts of the code to be changed. Maybe this can be tackled in a follow-up PR.

2021-07-07 11:47 UTC, kordano approved these changes
This looks good. Thanks for your contribution @MrEbbinghaus.

2021-07-08 13:50 UTC, merged