Datom and index metrics
replikativ/datahike pull request #515
Opened 2022-04-21 05:19 UTC by yflim

#### SUMMARY
Add datom and index metrics

#### Checks

##### Feature
- [ ] Implements an existing feature request. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Architecture Decision Record added 
- [ ] Formatting checked
- [ ] `CHANGELOG.md` updated

2022-04-21 16:44 UTC, yflim commented
Does it make sense to provide count and index metrics on database records besides DB (HistoricalDB, FilteredDB at the moment)? Thought it could be useful, hence -metrics is in the IDB protocol for now so it can be implemented across database records.

2022-05-05 10:20 UTC, jsmassa requested changes
Lacks readability. 
I would really encourage you to use more [threading macros](https://clojure.org/guides/threading_macros) and not to hesitate to put expressions on a new line when things get too nested.
Also, even if it is just to keep some order, within a hash-map, please, stick to either putting the value next to its key or below it, but don't mix it up!

2022-05-05 10:20 UTC, jsmassa commented on src/datahike/db.cljc
> +     (reduce + 0 (map count (vals (filter-idxed-attrs (group-by :a (-seq (.-temporal-eavt db)))))))}))
Use `->>`

2022-05-05 10:20 UTC, jsmassa commented on src/datahike/db.cljc
> +                                   (fn [ecs e c] (if (ecs e) (update ecs e #(+ % c)) (assoc ecs e c)))
`if` statement should have if and else branches in lines on their own

2022-05-05 10:20 UTC, jsmassa commented on src/datahike/db.cljc
> +     :avet-count (reduce + 0 (map second (filter-idxed-attrs per-attr-counts)))
Potentially use `->>`

2022-05-05 10:20 UTC, jsmassa commented on src/datahike/db.cljc
> +                                (map #(into {} (map (fn [[e d]] [e (count d)]) %)) (vals attr-entity-counts)))
Hard to read: Which `map` has `(vals attr-entity-counts)` as parameter? The first or the second one? It's not obvious with just one look. Solution: threading macro or separate line for collection.

2022-05-07 21:47 UTC, yflim commented
> Lacks readability. I would really encourage you to use more [threading macros](https://clojure.org/guides/threading_macros) and not to hesitate to put expressions on a new line when things get too nested. Also, even if it is just to keep some order, within a hash-map, please, stick to either putting the value next to its key or below it, but don't mix it up!

Then again, why do all that instead of simply `(group-by :a)` and `(group-by :e)` on `(-seq (.-eavt db))` (invoked here anyway) and its temporal equivalent? This buys neither memory nor performance, I think. Am I missing or forgetting anything?

2022-05-09 14:29 UTC, jsmassa commented
What do you mean? Do you want to somehow include it in the `-seq` function or count everything stepping through the sequence just once?

2022-05-09 17:57 UTC, yflim commented
I mean something like (abridged for clarity):
`(let [eavt-datoms (-seq (.-eavt db))]
    {:per-attr-counts (->> (vals (group-by :a eavt-datoms))
                                           (map count))
     :per-entity-counts (->> (vals (group-by :e eavt-datoms))
                                              (map count))})`

2022-05-10 23:25 UTC, jsmassa commented
Sure, you can write it like that. I don't think it has performance benefits either though. I would expect that it will still step through the sequence twice; once for each of the grouping operations. To only step through it once, you could implement a big reduce operation with the empty count-map as initial value and then set/increase the counts with `assoc-in` or `update-in` operations.

It definitely makes sense to implement one function and then call it for the current and for the temporal indices. 

I also think, this implementation will not result in what you actually wanted to get. By calling `vals`, you lose the information of which attribute the count corresponds to. I think, what you would want is something like:
```
(->> eavt-datoms
     (group-by :e)
     (map-vals count))
```
(The `map-vals` function is not part of the clojure core library, but can be pulled in with the [medley](http://weavejester.github.io/medley/medley.core.html#var-map-vals) library or has to be written yourself.)

Btw, note how I am using even more lines of code here for the threading macro. This is the easiest to read: start with the object you want to transform on the first line and then list each transformation from top to bottom each on their own line even if it's something short like `vals`.

2022-08-31 13:55 UTC, jsmassa commented on src/datahike/db.cljc
> +        filter-idxed-attrs (fn [attr-counts] (filter (fn [[a v]] (-> (:db/index (.-rschema db))
Why is this a separate function? Isn't it just needed once?

2022-10-04 09:38 UTC, jsmassa submitted a review, later dismissed

2022-10-04 09:50 UTC, jsmassa approved these changes

2022-10-04 09:50 UTC, merged