chore: remove cljs dep from prod
replikativ/datahike pull request #614
Opened 2023-03-10 21:27 UTC by jsmassa

#### SUMMARY
Move ClojureScript dependency to `:cljs` alias.

#### ADDITIONAL INFORMATION
- The ClojureScript dependency is quite large
  - see discussion #613
- There is currently no ClojureScript support in Datahike (version 0.6.1538)
- Most Clojure/ClojureScript expect ClojureScript library to be provided (e.g. [datascript](https://github.com/tonsky/datascript/blob/1a405721cb2226a28678066b176a5326c264153e/project.clj#L11), [environ](https://github.com/weavejester/environ/blob/aa90997b38bb8070d94dc4a00a14e656eb5fc9ae/environ/project.clj#L8))

2023-03-28 09:28 UTC, whilo requested changes
Cheshire is used by libdatahike, so you should probably move it as a dependency into its profile, otherwise looks good. https://github.com/replikativ/datahike/blob/main/libdatahike/src/datahike/impl/libdatahike.clj#L3

2023-03-28 13:35 UTC, jsmassa commented
We are getting into trouble building the api docs when moving the `cheshire` lib back to an alias. Unless it is an big dependency I wouldn't move it away from the common libs because of this issue. We could introduce a `projects` directory similar to the way it is in polylith to isolate the cli namespace and then we can easily drop the package that is only needed there but as long as it is mixed in with the rest of datahike it can be quite confusing not to be able to load the namespace with the common dependencies.

2023-07-22 17:12 UTC, TimoKramer approved these changes
thanks, merge it please. problem is though, that in each replikativ-dep there is clojurescript as dep :)

2023-07-22 17:12 UTC, TimoKramer commented on deps.edn
these lines are not needed anymore, just rebase and they are gone into the alias

2023-10-02 07:23 UTC, closed without merging